### ISSUE TITLE
a fix for the columns issue

### ISSUE THREAD

**Issue by hadrielk** [gaddman/wireshark-tcpextend#2]
Hi,
one of your known issues says: "When the columns in Wireshark are changed in any way (added/removed/renamed), the calculations may get stuffed up, in which case you'll need to restart Wireshark."

That's because modifying the columns triggers a a fresh re-dissection, but your Lua tables will already be set with info. (and I believe the `pinfo.visited` will be cleared for this full re-dissection)  Likewise you'll probably have issues with users opening new files without quitting Wireshark.

The way to fix all that is to reset your Lua tables (clear them) when your `Proto` is reset, which means creating a `proto.init()` callback function and resetting your tables in there.

Like for example, replace the lines toward the top of the script that set all the `tcpextend_stats` subtables with `= {}`, to instead just be this:

```
local function reset_stats()
    tcpextend_stats = {}
    tcpextend_stats.client_time = {}
    tcpextend_stats.server_time = {}
    tcpextend_stats.client_port = {}
    tcpextend_stats.server_port = {}
    tcpextend_stats.client_win = {}
    tcpextend_stats.server_win = {}
    tcpextend_stats.client_bsp = {}
    tcpextend_stats.server_bsp = {}
    tcpextend_stats.client_ack = {}
    tcpextend_stats.server_ack = {}
    tcpextend_stats.client_len = {}
    tcpextend_stats.server_len = {}
    -- per packet
    tcpextend_stats.bif = {}
    tcpextend_stats.bsp = {}
    tcpextend_stats.txb = {}
    tcpextend_stats.pba = {}
    tcpextend_stats.delta = {}
end

function TCPextend_proto.init()
    reset_stats()
end
```

That `TCPextend_proto.init()` function will be invoked by Wireshark at the beginning, as well as when the file is closed, columns changed, etc.  In other words, in all the right places. :)

Also, you should move your `register_postdissector(TCPextend_proto)` line to be at the end of the file.

**Comment by gaddman** [comment]
Thanks @hadrielk. Still getting the hang of LUA/Wireshark, so suggestions are most welcome! I'll spend some time looking at your code for other tips.

**Comment by hadrielk** [comment]
No worries - your code is fine. :)
