### ISSUE TITLE
TCP Retransmission and OOO calculations for BIF 

### ISSUE THREAD

**Issue by kishan84** [gaddman/wireshark-tcpextend#4]
Hi Chris,
The features you added are amazing like BIF and bytes calculation for from push to push bit.As you have already mentioned about TCP Retransmission and OOO calculations,at present it just keep on adding to BIF during transmission and OOO, Is there any fix expected on this.

**Comment by gaddman** [comment]
Hi,
Yeah, I had a capture last week doing the same thing, so with you raising an issue that's double motivation to do something now. I'll take a look over the next couple of days.

And thanks for the comment, great to know it's of use to someone else!
cheers,
chris

**Comment by kishan84** [comment]
Hi,
Thanks for reply Chris,I will be waiting for next update.

On 24 August 2015 at 13:46, Christopher Gadd notifications@github.com
wrote:

> Hi,
> Yeah, I had a capture last week doing the same thing, so with you raising
> an issue that's double motivation to do something now. I'll take a look
> over the next couple of days.
> 
> And thanks for the comment, great to know it's of use to someone else!
> cheers,
> chris
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134087369
> .

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by gaddman** [comment]
Update 7940a08 should help (fix?) the bsp counting. bif is still broken during retransmissions (and also if you don't have relative seq numbers on)

**Comment by kishan84** [comment]
Thanks for update,i will check.if you could able to fix bif issue,it will
help tcp analysis a lot easier.Really appreciate.

On 25 August 2015 at 02:29, Christopher Gadd notifications@github.com
wrote:

> Update 7940a08
> https://github.com/gaddman/wireshark-tcpextend/commit/7940a0899fccd971ba735db4c0c43db6cd2f4b43
> should help (fix?) the bsp counting. bif is still broken during
> retransmissions (and also if you don't have relative seq numbers on)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134378600
> .

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by gaddman** [comment]
Commit 2a58e2d should fix the BIF counting, for both retransmissions and if you're using absolute sequence numbers. @kishan84 let me know if it looks OK now and I'll close this issue.

**Comment by kishan84** [comment]
Thanks chris,i will reply today,i just tried a capture and it looks,you did
it. Surreal.Amazing.

On 26 August 2015 at 13:56, Christopher Gadd notifications@github.com
wrote:

> Commit 2a58e2d
> https://github.com/gaddman/wireshark-tcpextend/commit/2a58e2d43bbc2481dc5f9d9b8dc2a8e61bdf4504
> should fix the BIF counting, for both retransmissions and if you're using
> absolute sequence numbers. @kishan84 https://github.com/kishan84 let me
> know if it looks OK now and I'll close this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134895709
> .

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by kishan84** [comment]
I wish if i could be a developer like you,you did it.This script can bring
down a lot of performance tshoot time.I have no words to descript.Amazing

On 27 August 2015 at 10:02, kishan pandey kishan84p@gmail.com wrote:

> Thanks chris,i will reply today,i just tried a capture and it looks,you
> did it. Surreal.Amazing.
> 
> On 26 August 2015 at 13:56, Christopher Gadd notifications@github.com
> wrote:
> 
> > Commit 2a58e2d
> > https://github.com/gaddman/wireshark-tcpextend/commit/2a58e2d43bbc2481dc5f9d9b8dc2a8e61bdf4504
> > should fix the BIF counting, for both retransmissions and if you're using
> > absolute sequence numbers. @kishan84 https://github.com/kishan84 let
> > me know if it looks OK now and I'll close this issue.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134895709
> > .
> 
> ## 
> 
> Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by kishan84** [comment]
This will also help in understanding tcp/ip stack behaviour in detail.great

On 27 August 2015 at 22:53, kishan pandey kishan84p@gmail.com wrote:

> I wish if i could be a developer like you,you did it.This script can bring
> down a lot of performance tshoot time.I have no words to descript.Amazing
> 
> On 27 August 2015 at 10:02, kishan pandey kishan84p@gmail.com wrote:
> 
> > Thanks chris,i will reply today,i just tried a capture and it looks,you
> > did it. Surreal.Amazing.
> > 
> > On 26 August 2015 at 13:56, Christopher Gadd notifications@github.com
> > wrote:
> > 
> > > Commit 2a58e2d
> > > https://github.com/gaddman/wireshark-tcpextend/commit/2a58e2d43bbc2481dc5f9d9b8dc2a8e61bdf4504
> > > should fix the BIF counting, for both retransmissions and if you're using
> > > absolute sequence numbers. @kishan84 https://github.com/kishan84 let
> > > me know if it looks OK now and I'll close this issue.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134895709
> > > .
> > 
> > ## 
> > 
> > Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)
> 
> ## 
> 
> Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by gaddman** [comment]
Great to hear it's working out for you! Enjoy, and just raise another issue if you find more problems, or looking for some extra fields. Closing this issue now.

**Comment by kishan84** [comment]
Great,definitely

On 28 August 2015 at 02:39, Christopher Gadd notifications@github.com
wrote:

> Great to hear it's working out for you! Enjoy, and just raise another
> issue if you find more problems, or looking for some extra fields. Closing
> this issue now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-135555608
> .

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by kishan84** [comment]
Hi Chris,
Hope you are doing well,in wireshark there is no way to identify sessions
where only syn is received and syn ack received.Can you help me in this.

On 28 August 2015 at 09:41, kishan pandey kishan84p@gmail.com wrote:

> Great,definitely
> 
> On 28 August 2015 at 02:39, Christopher Gadd notifications@github.com
> wrote:
> 
> > Great to hear it's working out for you! Enjoy, and just raise another
> > issue if you find more problems, or looking for some extra fields. Closing
> > this issue now.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-135555608
> > .
> 
> ## 
> 
> Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

## 

Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by gaddman** [comment]
That's an interesting one, I'm not aware of any way. Would be good to ask over at the [Wireshark forums](https://ask.wireshark.org/)

**Comment by kishan84** [comment]
Hi Christopher,
After long time Need one help, I want to filter all session where we have
received SYN packet but no SYN ACK response received.Like in HTTP we have
filter http.response_in ( column Response in frame) similarly for all Three
way handshake can we make a filter like SYN-ACK IN FRAME and number and
then we can filter it based ! syn-ack.response_in.

This is very useful in day to day troubleshooting.Will looking for your
support.

On 24 August 2015 at 13:46, Christopher Gadd <notifications@github.com>
wrote:

> Hi,
> Yeah, I had a capture last week doing the same thing, so with you raising
> an issue that's double motivation to do something now. I'll take a look
> over the next couple of days.
>
> And thanks for the comment, great to know it's of use to someone else!
> cheers,
> chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaddman/wireshark-tcpextend/issues/4#issuecomment-134087369>
> .
>



-- 
Shivkrishna.L. Pandey (Sr.Network /Security Engineer.)

**Comment by gaddman** [comment]
Hi @kishan84, can you create a new issue for this? Seems like an interesting idea.

**Comment by gaddman** [comment]
@kishan84 I've added a new field which should help you do what you're after - ack_frame.
