### ISSUE TITLE
hi i have the same port as you what does it do ?

### ISSUE THREAD

**Issue by minanagehsalalma** [gaddman/wireshark-tcpextend#6]
port : 37443

and i also have port 37215 opened which is obviously used for upnp

what does the first port do ?
@gaddman thanks in advance

**Comment by minanagehsalalma** [comment]
https://github.com/gaddman/RG-fun/blob/master/index.md

**Comment by gaddman** [comment]
Just checked and it seems to be the HTTPS version of port 37215. For example, these two requests get identical content:
```
wget -O /tmp/upnp-37215 http://192.168.1.1:37215/upnpdev.xml
wget --no-check-certificate -O /tmp/upnp-37443 https://192.168.1.1:37443/upnpdev.xml
````
I've allowed issues on that other repo, and updated the page with this info, so anything else post there.
cheers!
